In [2]:
#creating NumPy  or N-Dimentional Arrays 
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [3]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
arr6=np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [11]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [12]:
arr8=arr7.copy()

In [13]:
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [14]:
'''Properties and Attributes 
1. shape 
2. nDim 
3. Size 
4. Itemsize
5. Dtype 
6. astype
'''

'Properties and Attributes \n1. shape \n2. nDim \n3. Size \n4. Itemsize\n5. Dtype \n6. astype\n'

In [15]:
arr1.shape

(5,)

In [16]:
arr2.shape

(3, 3)

In [17]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
arr9.shape

(2, 2, 2)

In [19]:
arr9.ndim

3

In [20]:
arr2.ndim

2

In [21]:
arr9.size

8

In [22]:
arr9.itemsize

4

In [23]:
arr8.itemsize

8

In [24]:
arr8.dtype

dtype('float64')

In [25]:
arr9.dtype

dtype('int32')

In [27]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [28]:
#Python List Vs NumPy Arrays 

In [29]:
 lista=range(100)
arr11=np.arange(100)

In [30]:
import sys

In [31]:
print(sys.getsizeof(34)*len(lista)) #34 here is just a number b/w 1 to 100 

2800


In [32]:
print(arr11.itemsize*arr11.size)

400


In [33]:
#numpY ARRAY  occupies less space 

In [34]:
import time 

In [48]:
x=range(10000000)
y=range(10000000,20000000)
start_time=time.time()
c=[(x,y) for x,y in zip(x,y)]
print(time.time()-start_time)

1.8204107284545898


In [51]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start_time=time.time()
c=a+b
print(time.time()-start_time)

0.53468918800354


In [52]:
#numpy is faster than python list 

In [53]:
#indexing slicing and iteration 

In [54]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [56]:
#to only get array with 2nd and 3rd column 
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [61]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [65]:
for i in arr12:
    print (i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [66]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [67]:
#NumPy Operations 

In [5]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [5]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [6]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [7]:
arr1>3

array([False, False, False,  True,  True,  True])

In [3]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [4]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [6]:
arr1.dot(arr2)

154